Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2204"
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "generic/debian11"
  end

  config.vm.define "arch" do |arch|
    arch.vm.box = "generic/arch"
  end

  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine318"
  end

  config.vm.define "freebsd" do |freebsd|
    freebsd.vm.box = "generic/freebsd11"
    freebsd.vm.provision "shell", inline: <<-SHELL
     sed -i '' 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     service sshd restart
    SHELL
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos8"
    centos.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd.service
    SHELL
  end
end
